MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "../pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  CONTRASTIVE_PATH: "../model/contrastive/simsiam-swinunet-Synapse_bsz12_epo100_lr6e-03_lrs-cos_wd1e-04_channel3.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7